blank_issues_enabled: false
contact_links:
  - name: Issue with AdMob on iOS only
    url: https://github.com/Poing-Studios/godot-admob-ios
    about: Check the iOS plugin repository.
  - name: Issue with AdMob on Godot Editor
    url: https://github.com/Poing-Studios/godot-admob-plugin
    about: Check the Godot plugin repository.
